site_name: Documentação da TODO-list
site_url: https://gabrieldev131.github.io/TODO-list/

theme:
  name: material
  palette:
    primary: indigo

nav:
  - Início: index.md
  - constitution: constitution.md
  - checklist-template: templates/checklist-template.md
  - constitution-template: templates/constitution-template.md
  - plan-template: templates/plan-template.md
  - spec-template: templates/spec-template.md
  - tasks-template: templates/tasks-template.md