site_name: Documentação da TODO-list
site_url: https://gabrieldev131.github.io/TODO-list/

theme:
  name: material
  palette:
    primary: indigo

nav:
  - Início: index.md
  - constitution: constitution.md
  - checklist: models/checklist.md
  - constitution-template: models/constitution-template.md
  - plan-template: models/plan-template.md
  - spec-template: models/spec-template.md
  - tasks-template: models/tasks-template.md