site_name: Documentação da TODO-list
site_url: https://gabrieldev131.github.io/TODO-list/

theme:
  name: material
  palette:
    primary: indigo

nav:
  - Início: index.md
  - Arquitetura: arquitetura.md
  - Workers: workers.md
  - API: api.md